title:              Veronika Post
email:              vep676@g.harvard.edu
description:        Information cannot be created or destroyed.
author:             Veronika Post
baseurl:            ""
url:                "https://v-post.github.io"

# Social Profiles
twitter_username:
github_username:   v-post
facebook_username:  
instagram_username:  
linkedin_username:   v-post

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
